Increment 13
lipandr/yandex_practicum_url_shortener pull request #12
Opened 2022-02-07 12:42 UTC by lipandr

2022-02-09 17:19 UTC, Bazys requested changes
добавить обработку ошибок с помощью `errors.Is(err, target error) bool`
и желательно обрабатывать `pgerrcode.UniqueViolation`

2022-02-09 17:19 UTC, Bazys commented on internal/app/batch.go
> +	var batch = make([]BatchRequest, 0)
в данном случае make не обязательно, ты просто объявил переменную var batch []BatchRequest
И анмаршалинг в эту переменную и пройдет

2022-02-09 17:19 UTC, Bazys commented on internal/app/batch.go
> +	var resp = make([]BatchResponse, 0)
а вот здесь у тебя есть размер массива. делаешь мейк с заданными размером и по индексу заполняешь данными. Условия нигде не стоят, аппендить в массив или нет.

2022-02-09 17:19 UTC, Bazys commented on internal/app/db_ping.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
просто из опыта - 1 секунда может быть маловато. Сервер может быть чем то сильно занят.

2022-02-09 17:19 UTC, Bazys commented on internal/app/encode_url.go
> +		if err == types.ErrKeyExists {
прямое сравнение не есть правильно!

2022-02-09 17:19 UTC, Bazys commented on internal/app/json_encode_url.go
> +		if err == types.ErrKeyExists {
аналогично

2022-02-09 17:19 UTC, Bazys commented on internal/app/middleware/auth.go
> +	key = []byte{193, 175, 17, 153, 220, 178, 229, 188, 18, 205, 215, 225, 202,
хардкод для учебной задачи допустим.
Но в реальной жизни ключи надо из вне.

2022-02-09 17:19 UTC, Bazys commented on internal/app/middleware/gzip.go
> +		if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
а может эту строчку в самое начало функции?
читаемость будет точно лучше

2022-02-09 17:19 UTC, Bazys commented on internal/service/db_dervice.go
> +		_, err := svc.db.Exec("INSERT INTO url (original, created_by) VALUES ($1, $2);", url, userID)
а как же `INSERT ... ON CONFLICT` из курса?

2022-02-09 17:19 UTC, Bazys commented on internal/storage/inmem/inmem.go
> +			//if seq, err := s.Get(seqList); err != nil {
тут не err наоборот, признак того что этот ключ в мапе есть
https://go.dev/blog/maps

2022-02-11 09:37 UTC, lipandr commented on internal/app/db_ping.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
увеличил до 5 секунд

2022-02-16 07:08 UTC, lipandr commented on internal/service/db_dervice.go
> +		_, err := svc.db.Exec("INSERT INTO url (original, created_by) VALUES ($1, $2);", url, userID)
я потратил очень много времени как применить UPSERT в учебном проекте и пока не разобрался как его применить - пока оставил как есть

2022-02-16 20:14 UTC, Bazys approved these changes

2022-02-16 20:41 UTC, merged